# Inserts a blank line between shell prompts
add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

[env_var.YAZI_LEVEL]
variable = "YAZI_LEVEL"
format = "[🦆](yellow) "

[git_metrics]
disabled = false

[cmd_duration]
disabled = false

[docker_context]
disabled = true

[kubernetes]
format = '[⛵$context](green) '
disabled = true

[sudo]
style = 'bold yellow'
symbol = '🧙'
disabled = false
